name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "staging", "production" ]
  pull_request:
    branches: [ "staging", "production" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: boudun/wordpress

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t wordpress


  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use commit number in image tag (default)
        run: |
          echo "## Building and pushing image with commit number"
          image_tag=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.1.${{github.run_number}}
          docker build . -t "$image_tag"
          docker push "$image_tag"

      - name: Build and push Docker image (optional)
        if: github.ref == 'refs/heads/production'
        run: |
          echo "## Building and pushing image without commit number"
          image_tag=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker build . -t "$image_tag"
          docker push "$image_tag"